# Generated by Django 6.0.7 on 2026-09-04 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ateliers/logos/')),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_commandes_mois', models.PositiveIntegerField(default=50)),
                ('max_utilisateurs', models.PositiveIntegerField(default=3)),
                ('support_prioritaire', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catalogue/')),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.atelier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='F', max_length=1)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Préférences, allergies textiles, etc.', null=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.atelier')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=50, null=True, unique=True)),
                ('description_vetement', models.TextField(help_text='Détails du modèle, modifications demandées, etc.')),
                ('photo_tissu', models.ImageField(blank=True, null=True, upload_to='commandes/tissus/')),
                ('photo_modele_custom', models.ImageField(blank=True, null=True, upload_to='commandes/modeles/')),
                ('prix_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours de confection'), ('PRET', 'Prêt à essayer / livrer'), ('LIVRE', 'Livré'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateField()),
                ('date_livraison_effective', models.DateField(blank=True, null=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.atelier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='core.client')),
                ('couturier_attribue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_attribuees', to=settings.AUTH_USER_MODEL)),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cataloguemodele')),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Mensuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(default='Mesures Standard', help_text='Ex: Boubou, Costume, Robe de mariée', max_length=100)),
                ('donnees', models.JSONField(default=dict, help_text='Paires clé/valeur des mesures en cm')),
                ('date_prise', models.DateField(auto_now_add=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.atelier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensurations', to='core.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money (Wave, Orange Money, Moov, MTN)'), ('CARTE', 'Carte Bancaire'), ('VIREMENT', 'Virement Bancaire'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20)),
                ('reference_transaction', models.CharField(blank=True, help_text='Numéro de transaction Mobile Money / Chèque', max_length=100, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.atelier')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.commande')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField()),
                ('atelier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='core.atelier')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planabonnement')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROPRIETAIRE', 'Propriétaire / Gérant'), ('TAILLEUR', 'Tailleur / Couturier'), ('RECEPTIONNISTE', 'Réceptionniste')], default='PROPRIETAIRE', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('atelier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='core.atelier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
