# Generated by Django 6.0.7 on 2026-09-04 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('categorie', models.CharField(choices=[('ACHAT_MATERIEL', 'Achat de tissu / mercerie'), ('SALAIRE', 'Salaires / Payes tailleurs'), ('LOYER', "Loyer de l'atelier"), ('FACTURES', 'Eau, Électricité, Internet'), ('AUTRE', 'Autre dépense')], default='AUTRE', max_length=30)),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.atelier')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
