# Generated by Django 6.0.7 on 2026-09-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='origine',
            field=models.CharField(blank=True, choices=[('recommandation', 'Recommandation'), ('boutique', 'Passant / Boutique'), ('publicite', 'Publicité'), ('bouche_a_oreille', 'Bouche à oreille'), ('reseaux_sociaux', 'Réseaux sociaux'), ('autre', 'Autre')], max_length=30, null=True, verbose_name="Canal d'acquisition"),
        ),
    ]
