# Generated by Django 6.0.7 on 2026-09-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='remise_type',
            field=models.CharField(blank=True, choices=[('MONTANT', 'Montant fixe'), ('POURCENTAGE', 'Pourcentage')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='remise_valeur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
