# Generated by Django 6.0.7 on 2026-09-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_commande_remise_type_commande_remise_valeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('BOUTON', 'Boutons'), ('FERMETURE', 'Fermetures / Zips'), ('BRODERIE', 'Broderies / Dentelles'), ('DOUBLURE', 'Doublures / Entoilages'), ('FIL', 'Fils spéciaux'), ('ELASTIQUE', 'Élastiques / Rubans'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unite', models.CharField(choices=[('PIECE', 'Pièce'), ('METRE', 'Mètre'), ('LOT', 'Lot'), ('KG', 'Kilogramme')], default='PIECE', max_length=10)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='accessoires/')),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.atelier')),
            ],
            options={
                'ordering': ['categorie', 'nom'],
            },
        ),
    ]
