# Generated by Django 6.0.7 on 2026-09-10 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_accessoire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cataloguemodele',
            options={'ordering': ['type_modele', 'nom']},
        ),
        migrations.RemoveField(
            model_name='commande',
            name='description_vetement',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='modele',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='photo_modele_custom',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='photo_tissu',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='prix_total',
        ),
        migrations.AddField(
            model_name='cataloguemodele',
            name='couleur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cataloguemodele',
            name='stock_pret_a_porter',
            field=models.PositiveIntegerField(default=0, help_text='Stock disponible pour le prêt-à-porter'),
        ),
        migrations.AddField(
            model_name='cataloguemodele',
            name='taille_disponible',
            field=models.CharField(blank=True, help_text='Ex: S, M, L, XL ou 38, 40, 42', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cataloguemodele',
            name='type_modele',
            field=models.CharField(choices=[('COUTURE', 'Couture sur mesure'), ('PRET_A_PORTER', 'Prêt-à-porter')], default='COUTURE', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessoire',
            name='categorie',
            field=models.CharField(choices=[('BOUTON', 'Boutons'), ('FERMETURE', 'Fermetures / Zips'), ('BRODERIE', 'Broderies / Dentelles'), ('DOUBLURE', 'Doublures / Entoilages'), ('FIL', 'Fils spéciaux'), ('ELASTIQUE', 'Élastiques / Rubans'), ('CHAUSSURE', 'Chaussures'), ('FOULARD', 'Foulards / Voiles'), ('BIJOU', 'Bijoux / Ornements'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='accessoire',
            name='unite',
            field=models.CharField(choices=[('PIECE', 'Pièce'), ('METRE', 'Mètre'), ('LOT', 'Lot'), ('KG', 'Kilogramme'), ('PAIRE', 'Paire')], default='PIECE', max_length=10),
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type_ligne', models.CharField(choices=[('COUTURE', 'Couture sur mesure'), ('PRET_A_PORTER', 'Prêt-à-porter'), ('ACCESSOIRE', 'Accessoire / Article')], default='COUTURE', max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True, help_text='Détails spécifiques à cette couture', null=True)),
                ('photo_tissu', models.ImageField(blank=True, null=True, upload_to='commandes/tissus/')),
                ('photo_modele_custom', models.ImageField(blank=True, null=True, upload_to='commandes/modeles/')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remise_type', models.CharField(blank=True, choices=[('MONTANT', 'Montant fixe'), ('POURCENTAGE', 'Pourcentage')], max_length=15, null=True)),
                ('remise_valeur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accessoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='core.accessoire')),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.atelier')),
                ('client_secondaire', models.ForeignKey(blank=True, help_text='Si cette couture est pour un autre client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_secondaires', to='core.client')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.commande')),
                ('couturier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_attribuees', to=settings.AUTH_USER_MODEL)),
                ('mensuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='core.mensuration')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='core.cataloguemodele')),
            ],
            options={
                'ordering': ['ordre', 'date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneAccessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accessoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='core.accessoire')),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.atelier')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoires_ligne', to='core.lignecommande')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
