# Generated by Django 6.0.7 on 2026-09-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cataloguemodele_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensuration',
            options={'ordering': ['-date_prise']},
        ),
        migrations.AddField(
            model_name='mensuration',
            name='beneficiaire',
            field=models.CharField(blank=True, help_text='Nom de la personne mesurée. Vide = le client lui-même.', max_length=150),
        ),
        migrations.AddField(
            model_name='mensuration',
            name='genre_mesure',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=10),
        ),
        migrations.AddField(
            model_name='mensuration',
            name='lien_parente',
            field=models.CharField(choices=[('MOI', 'Le client lui-même'), ('EPOUX', 'Époux / Épouse'), ('ENFANT', 'Enfant'), ('PARENT', 'Parent'), ('FRERE_SOEUR', 'Frère / Sœur'), ('AMI', 'Ami(e)'), ('AUTRE', 'Autre')], default='MOI', help_text='Lien entre le client et la personne mesurée', max_length=20),
        ),
    ]
