# Generated by Django 6.0.7 on 2026-09-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_mensuration_options_mensuration_beneficiaire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande', '-id']},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['date_paiement']},
        ),
        migrations.AlterField(
            model_name='atelier',
            name='devise',
            field=models.CharField(choices=[('FCFA', 'Franc CFA (FCFA)'), ('EUR', 'Euro (€)'), ('USD', 'Dollar ($)'), ('GNF', 'Franc Guinéen (GNF)'), ('MAD', 'Dirham Marocain (MAD)'), ('XOF', 'Franc CFA Ouest (XOF)')], default='FCFA', max_length=10),
        ),
    ]
