# Generated by Django 6.0.7 on 2026-09-14 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_commande_options_alter_paiement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoire',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=5, help_text='Seuil en dessous duquel le stock est signalé comme faible'),
        ),
        migrations.AddField(
            model_name='atelier',
            name='seuil_stock_faible',
            field=models.PositiveIntegerField(default=5, help_text="Seuil d'alerte pour le stock des articles et accessoires"),
        ),
        migrations.AddField(
            model_name='cataloguemodele',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=3, help_text='Seuil en dessous duquel le stock est signalé comme faible'),
        ),
        migrations.AddField(
            model_name='commande',
            name='stock_decremente',
            field=models.BooleanField(default=False, help_text='Le stock a déjà été retiré pour cette commande.'),
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type_mouvement', models.CharField(choices=[('VENTE', 'Sortie — Vente directe'), ('ANNULATION', 'Entrée — Annulation de vente'), ('REAPPRO', 'Entrée — Réapprovisionnement'), ('PERTE', 'Sortie — Perte / Casse'), ('INVENTAIRE', "Correction d'inventaire"), ('CONSOMMATION', 'Sortie — Consommation atelier')], max_length=20)),
                ('quantite', models.IntegerField(help_text='Négatif pour une sortie, positif pour une entrée')),
                ('stock_avant', models.PositiveIntegerField(default=0)),
                ('stock_apres', models.PositiveIntegerField(default=0)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('accessoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='core.accessoire')),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.atelier')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='core.commande')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='core.cataloguemodele')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_creation'],
            },
        ),
    ]
