# Generated by Django 6.0.7 on 2026-09-14 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_accessoire_seuil_alerte_atelier_seuil_stock_faible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('matricule', models.CharField(blank=True, max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('telephone_urgence', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employes/')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('poste', models.CharField(choices=[('COUTURIER', 'Couturier / Tailleur'), ('BRODEUR', 'Brodeur'), ('COUPEUR', 'Coupeur'), ('FINISSEUR', 'Finisseur / Repassage'), ('APPRENTI', 'Apprenti'), ('VENDEUR', 'Vendeur / Boutique'), ('AUTRE', 'Autre')], default='COUTURIER', max_length=20)),
                ('specialites', models.CharField(blank=True, help_text='Ex : Boubou, Costume homme, Robe de mariée', max_length=200)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('CONGE', 'En congé'), ('SUSPENDU', 'Suspendu'), ('PARTI', 'Ne travaille plus ici')], default='ACTIF', max_length=20)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('type_remuneration', models.CharField(choices=[('FIXE', 'Salaire fixe mensuel'), ('PIECE', 'Paiement à la pièce'), ('MIXTE', 'Fixe + commission à la pièce')], default='FIXE', max_length=10)),
                ('salaire_mensuel', models.DecimalField(decimal_places=2, default=0, help_text='Montant du fixe mensuel (si applicable)', max_digits=10)),
                ('commission_type', models.CharField(blank=True, choices=[('MONTANT', 'Montant fixe par pièce'), ('POURCENTAGE', 'Pourcentage du prix de la pièce')], default='MONTANT', max_length=15)),
                ('commission_valeur', models.DecimalField(decimal_places=2, default=0, help_text='Montant par pièce, ou pourcentage du prix de la couture', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.atelier')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('salaire_fixe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commissions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nb_pieces', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PAYEE', 'Payée')], default='BROUILLON', max_length=15)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('mode_paiement', models.CharField(default='ESPECES', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.atelier')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paies', to='core.employe')),
            ],
            options={
                'verbose_name': 'Paie',
                'verbose_name_plural': 'Paies',
                'ordering': ['-periode_fin', '-id'],
            },
        ),
    ]
