# Generated by Django 6.0.7 on 2026-09-14 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employe_paie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='employe_attribue',
            field=models.ForeignKey(blank=True, help_text='Employé responsable de toute la commande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_employe', to='core.employe'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='commission_versee',
            field=models.BooleanField(default=False, help_text='La commission de cette pièce a déjà été payée'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='date_debut_travail',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='date_fin_travail',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='employe',
            field=models.ForeignKey(blank=True, help_text="Employé de l'atelier chargé de cette couture", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_travail', to='core.employe'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='etat_travail',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='A_FAIRE', help_text='Avancement de cette pièce', max_length=15),
        ),
        migrations.AlterField(
            model_name='commande',
            name='couturier_attribue',
            field=models.ForeignKey(blank=True, help_text='Compte utilisateur (ancien système, conservé)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_attribuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='couturier',
            field=models.ForeignKey(blank=True, help_text='Compte utilisateur (ancien système, conservé)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_attribuees', to=settings.AUTH_USER_MODEL),
        ),
    ]
