# Generated by Django 6.0.7 on 2026-09-15 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_commande_employe_attribue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'ordering': ['-est_fondateur', 'role', 'user__first_name']},
        ),
        migrations.AddField(
            model_name='profil',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profil',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='est_fondateur',
            field=models.BooleanField(default=False, help_text="Compte créé à l'inscription. Masqué dans la liste."),
        ),
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur (Propriétaire)'), ('GESTIONNAIRE', "Gestionnaire de l'atelier"), ('COMPTABLE', 'Comptable')], default='GESTIONNAIRE', max_length=20),
        ),
    ]
