# Generated by Django 6.1.1 on 2026-09-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_planabonnement_description_est_populaire_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='planabonnement',
            name='duree_mois',
            field=models.PositiveSmallIntegerField(choices=[(0, "Période d'essai (14 jours)"), (3, '3 mois'), (6, '6 mois'), (12, '12 mois (annuel)')], default=3, help_text="Période d'essai (14 jours), 3, 6 ou 12 mois."),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='fonctionnalites_exclues',
            field=models.TextField(blank=True, default='', help_text='Fonctionnalités NON permises, une par ligne.'),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='fonctionnalites_incluses',
            field=models.TextField(blank=True, default='', help_text='Fonctionnalités PERMISES, une par ligne.'),
        ),
    ]
