# Generated by Django 6.1.1 on 2026-09-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_plan_fonctionnalites_duree'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationLomopay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_publique', models.CharField(max_length=120)),
                ('cle_secrete', models.CharField(max_length=120)),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour désactiver le paiement en ligne sans effacer les clés.')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration LomoPay',
            },
        ),
        migrations.CreateModel(
            name='LomoPayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField()),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('external_reference', models.CharField(max_length=64, unique=True)),
                ('id_lomopay', models.CharField(blank=True, default='', max_length=64)),
                ('checkout_url', models.URLField(blank=True, default='', max_length=500)),
                ('methode', models.CharField(blank=True, default='', max_length=40)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Payé'), ('FAILED', 'Échoué / annulé')], default='PENDING', max_length=10)),
                ('evenement_id', models.CharField(blank=True, default='', help_text="Dernier id d'événement webhook traité (anti-doublon).", max_length=64)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_lomopay', to='core.atelier')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.planabonnement')),
            ],
            options={
                'verbose_name': 'Transaction LomoPay',
                'ordering': ['-cree_le'],
            },
        ),
    ]
