# Generated by Django 6.0.7 on 2026-08-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formuleabonnement',
            name='est_populaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formuleabonnement',
            name='fonctionnalites_exclues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formuleabonnement',
            name='fonctionnalites_incluses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='formule_abonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boutiques', to='saas_admin.formuleabonnement'),
        ),
        migrations.AlterField(
            model_name='formuleabonnement',
            name='duree_mois',
            field=models.PositiveIntegerField(default=1, help_text='Durée en mois (ex: 1 pour mensuel, 12 pour annuel)'),
        ),
    ]
