# Generated by Django 6.1.1 on 2026-09-18 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_planabonnement_description_est_populaire_actif'),
        ('saas_admin', '0002_formuleabonnement_est_populaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('mode', models.CharField(choices=[('ESPECES', 'Espèces'), ('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('VIREMENT', 'Virement bancaire'), ('CARTE', 'Carte bancaire'), ('AUTRE', 'Autre')], default='ESPECES', max_length=20)),
                ('reference', models.CharField(blank=True, default='', help_text='N° de transaction Orange Money / Wave, chèque, etc.', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('mois_couverts', models.PositiveIntegerField(default=1)),
                ('prolonge', models.BooleanField(default=True, help_text="Prolonger automatiquement l'abonnement après encaissement.")),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_abonnement', to='core.atelier')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_abonnement_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
