# Generated by Django 5.2 on 2026-07-04 21:00

from django.db import migrations, models
import django.db.models.deletion
import datetime

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tissu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=50)),
                ('prix_metre', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Mensuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('tour_poitrine', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de poitrine (cm)')),
                ('tour_taille', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de taille (cm)')),
                ('tour_hanches', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de hanches (cm)')),
                ('longueur_manche', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur manche (cm)')),
                ('longueur_jambe', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur jambe (cm)')),
                ('encolure', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Encolure (cm)')),
                ('epaule', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Épaule (cm)')),
                ('tour_manche', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de manche (cm)')),
                ('longueur_taille', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur de taille (cm)')),
                ('longueur_bassin', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur bassin (cm)')),
                ('bassin', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bassin (cm)')),
                ('longueur_genou', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur de genou (cm)')),
                ('tour_genou', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de genou (cm)')),
                ('longueur_camisole', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur camisole (cm)')),
                ('longueur_jupe', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur jupe (cm)')),
                ('longueur_robe', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur robe (cm)')),
                ('longitude_haut', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longitude haut (cm)')),
                ('epaule_homme', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Épaules (cm) - Boubou')),
                ('manche_boubou', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Manches (cm)')),
                ('tour_manche_homme', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de manche (cm)')),
                ('coude', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Coude (cm)')),
                ('poitrine_homme', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Poitrine (cm)')),
                ('longueur_boubou', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur du boubou (cm)')),
                ('poignet', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Poignet (cm)')),
                ('tour_fesses', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de fesses (cm)')),
                ('ceinture', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Ceinture (cm)')),
                ('cuisse', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Cuisse (cm)')),
                ('longueur_pantalon', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur du pantalon (cm)')),
                ('ds', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='DS (cm)')),
                ('bas_pantalon', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bas du pantalon (cm)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensurations', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vetement', models.CharField(choices=[('costume', 'Costume'), ('chemise', 'Chemise'), ('robe', 'Robe'), ('pantalon', 'Pantalon'), ('veste', 'Veste'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('metrage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('encours', 'En cours'), ('termine', 'Terminé'), ('livre', 'Livré'), ('attente', 'En attente')], default='brouillon', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('tissu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tissu')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('fournitures', 'Fournitures'), ('equipement', 'Équipement'), ('loyer', 'Loyer'), ('salaire', 'Salaire'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(default=datetime.date.today)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.commande')),
            ],
        ),
    ]